package com.example.tripplanner.dto;

public enum ErrorCode {
    DESTINATION_NOT_FOUND,
    DESTINATION_ALREADY_EXISTS,
    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,
    FAVOURITE_DESTINATION_ALREADY_EXISTS,
    FAVOURITE_DESTINATION_NOT_FOUND,
    TRIP_NOT_FOUND,
    GENERIC_ERROR
}
