spring.config.import=optional:file:.env[.properties]

spring.application.name=tripplanner

spring.datasource.url=jdbc:postgresql://localhost:5432/trip_planner
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${SERVER_PORT}
server.address=127.0.0.1

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}